language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install mock"
  - "pip install coveralls"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to run tests
script: nosetests  -v --with-coverage --cover-package=ToLsTOy

after_success:
  coveralls



