environment:
  matrix:

    # Python 2.7.10 is the latest version and is not pre-installed.

    - PYTHON: "C:\\Python27"

install:
  - "%PYTHON%\\python.exe -m pip install mock"
  - "%PYTHON%\\python.exe -m pip install nose"

build: false

test_script:
  - "%PYTHON%\\python.exe -m nose"
